import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {
  ClerkProvider
} from '@clerk/nextjs'
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";

const AppFont=Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "AI Course generator app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${AppFont.className} flex flex-col min-h-screen`}>
          <Provider>
            <main className="flex-1">
              {children}
            </main>
            <Footer />
            <Toaster position="top-center" richColors />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
