import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const AppFont=Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "AI Course generator app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={AppFont.className}
      >
        {children}
      </body>
    </html>
  );
}
